Big tidy up and make consistent

diff --git a/bin/check_hash b/bin/check_hash
--- a/bin/check_hash
+++ b/bin/check_hash
@@ -2,31 +2,45 @@
 
 set -e
 
-SAVEIFS=$IFS
+SAVEIFS=${IFS}
 IFS=$(echo -en "\n\b")
 
-dir=$(readlink -f $1)
-hashfilename=${2:-checksum.md5}
+print_usage() {
+    echo "check_hash: validate all files in a directory against the MD5 hash"
+    echo ""
+    echo "  How to use:"
+    echo "  check_hash <input_directory> [hash_filename]"
+}
 
-if [ ! -d "$dir" ]; then
-    echo "Directory not found"
+
+INPUT_DIR_ARG=$1
+HASH_FILENAME=${2:-checksum.md5}
+
+if [ -z "${INPUT_DIR_ARG}" ]; then
+    print_usage
     exit 1
 fi
 
-pushd $dir
+INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
 
-if [ ! -f "$hashfilename" ]; then
-    echo "Hash file $hashfilename does not exist"
+if [ ! -d "${INPUT_DIR}" ]; then
+    echo "Input directory not found at: ${INPUT_DIR}"
+    print_usage
+    exit 1
+fi
+
+if [ ! -f "${HASH_FILENAME}" ]; then
+    echo "Could not find hash with name: ${HASH_FILENAME}"
+    print_usage
     exit 1
 fi
 
 # Hashes are usually created on the same Windows system that was used to rip
 # the CD, so it needs converting into a sensible format for checking.
-cat ./$hashfilename | dos2unix | md5sum --check --status --warn --strict
+cat ./${HASH_FILENAME} | dos2unix | md5sum --check --status --warn --strict
 if [ "$?" -ne "0" ]; then
+    echo "Error: hash did not match"
     exit 1
 fi
 
-IFS=$SAVEIFS
-
-exit 0
+IFS=${SAVEIFS}
diff --git a/bin/flac_to_mp3 b/bin/flac_to_mp3
--- a/bin/flac_to_mp3
+++ b/bin/flac_to_mp3
@@ -2,43 +2,69 @@
 
 set -e
 
-SAVEIFS=$IFS
+SAVEIFS=${IFS}
 IFS=$(echo -en "\n\b")
 
-dir=$(readlink -f $1)
-output=$(readlink -f $2)
-quality=${3:-2}
+print_usage() {
+    echo "flac_to_mp3: converts all FLAC files in a directory to MP3, using LAME"
+    echo ""
+    echo "  How to use:"
+    echo "  flac_to_mp3 <input_directory> <output_directory> [lame-quality, default 2]"
+}
 
-if [ ! -d "$dir" ] || [ ! -d "$output" ]; then
-    echo "Directory not found"
+INPUT_DIR_ARG=$1
+OUTPUT_DIR_ARG=$2
+LAME_QUALITY=${3:-2}
+
+if [ -z "${INPUT_DIR_ARG}" ] || [ -z "${OUTPUT_DIR_ARG}" ]; then
+    print_usage
     exit 1
 fi
 
-output_path="$output/${dir##*/}"
-echo 'Creating directory at' $output_path
-mkdir -p "$output_path"
+INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
+OUTPUT_DIR=$(readlink -f "${OUTPUT_DIR_ARG}")
 
-flacs=$(find $dir -type f -name "*.flac" | sort --numeric-sort)
+if [ ! -d "${INPUT_DIR}" ]; then
+    echo "Input directory not found at: ${INPUT_DIR}"
+    print_usage
+    exit 1
+fi
 
-for flac_path in $flacs
-do
-    flac_name=${flac_path##*/}
-    mp3_name="${flac_name%flac}mp3"
-    output_mp3_path="$output_path/$mp3_name"
+if [ ! -d "${OUTPUT_DIR}" ]; then
+    echo "Output directory not found at: ${OUTPUT_DIR}"
+    print_usage
+    exit 1
+fi
 
-    artist=$(metaflac "$flac_path" --show-tag=ARTIST | sed s/.*=//g)
-    title=$(metaflac "$flac_path" --show-tag=TITLE | sed s/.*=//g)
-    album=$(metaflac "$flac_path" --show-tag=ALBUM | sed s/.*=//g)
-    genre=$(metaflac "$flac_path" --show-tag=GENRE | sed s/.*=//g)
-    tracknumber=$(metaflac "$flac_path" --show-tag=TRACKNUMBER | sed s/.*=//g)
-    date=$(metaflac "$flac_path" --show-tag=DATE | sed s/.*=//g)
 
-    echo "Converting $flac_path to $output_mp3_path"
-    flac --stdout --silent --decode $flac_path \
-        | lame -V $quality --vbr-new - "$output_mp3_path"
-    id3v2 -t "$title" -T "$tracknumber" -a "$artist" -A "$album" -g "$genre" -y "$date" "$output_mp3_path"
+INPUT_FILES=$(find ${INPUT_DIR} -type f -name "*.wav" | sort --numeric-sort)
+
+echo "Using lame quality setting: ${LAME_QUALITY}"
+
+for INPUT_FILEPATH in ${INPUT_FILES}; do
+    INPUT_FILENAME=${INPUT_FILEPATH##*/}
+    OUTPUT_FILENAME="${INPUT_FILENAME%wav}mp3"
+    OUTPUT_FILEPATH="${OUTPUT_DIR}/${OUTPUT_FILENAME}"
+
+    TRACK_ARTIST=$(metaflac "${INPUT_FILEPATH}" --show-tag=ARTIST | sed s/.*=//g)
+    TRACK_TITLE=$(metaflac "${INPUT_FILEPATH}" --show-tag=TITLE | sed s/.*=//g)
+    TRACK_ALBUM=$(metaflac "${INPUT_FILEPATH}" --show-tag=ALBUM | sed s/.*=//g)
+    TRACK_GENRE=$(metaflac "${INPUT_FILEPATH}" --show-tag=GENRE | sed s/.*=//g)
+    TRACK_TRACKNUMBER=$(metaflac "${INPUT_FILEPATH}" --show-tag=TRACKNUMBER | sed s/.*=//g)
+    TRACK_DATE=$(metaflac "${INPUT_FILEPATH}" --show-tag=DATE | sed s/.*=//g)
+
+    echo "Converting ${INPUT_FILEPATH} to ${OUTPUT_FILEPATH}"
+
+    flac --stdout --silent --decode ${INPUT_FILEPATH} \
+        | lame --silent -V ${LAME_QUALITY} --vbr-new - "${OUTPUT_FILEPATH}"
+    id3v2 \
+        -t "${TRACK_TITLE}" \
+        -T "${TRACK_TRACKNUMBER}" \
+        -a "${TRACK_ARTIST}" \
+        -A "${TRACK_ALBUM}" \
+        -g "${TRACK_GENRE}" \
+        -y "${TRACK_DATE}" \
+        "${OUTPUT_FILEPATH}"
 done
 
-IFS=$SAVEIFS
-
-exit 0
+IFS=${SAVEIFS}
diff --git a/bin/flac_to_ogg b/bin/flac_to_ogg
--- a/bin/flac_to_ogg
+++ b/bin/flac_to_ogg
@@ -5,49 +5,64 @@ set -e
 SAVEIFS=$IFS
 IFS=$(echo -en "\n\b")
 
-dir=$(readlink -f $1)
-output=$(readlink -f $2)
+print_usage() {
+    echo "flac_to_ogg: converts all FLAC files in a directory to OGG, using oggenv"
+    echo ""
+    echo "  How to use:"
+    echo "  flac_to_ogg <input_directory> <output_directory> [ogg-quality, default 5]"
+
+INPUT_DIR_ARG=$1
+OUTPUT_DIR_ARG=$2
+OGG_QUALITY=${3:-2}
+
 # Most users agree -q 5 achieves transparency, if the source is the original or
 # lossless: http://wiki.hydrogenaud.io/index.php?title=Recommended_Ogg_Vorbis
-quality=${3:-5}
 
-if [ ! -d "$dir" ] || [ ! -d "$output" ]; then
-    echo "Directory not found"
+if [ -z "${INPUT_DIR_ARG}" ] || [ -z "${OUTPUT_DIR_ARG}" ]; then
+    print_usage
     exit 1
 fi
 
-output_path="$output/${dir##*/}"
-echo 'Creating directory at' $output_path
-mkdir -p "$output_path"
+INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
+OUTPUT_DIR=$(readlink -f "${OUTPUT_DIR_ARG}")
 
-flacs=$(find $dir -type f -name "*.flac" | sort --numeric-sort)
+if [ ! -d "${INPUT_DIR}" ]; then
+    echo "Input directory not found at: ${INPUT_DIR}"
+    print_usage
+    exit 1
+fi
 
-for flac_path in $flacs
-do
-    flac_name=${flac_path##*/}
-    ogg_name="${flac_name%flac}ogg"
-    output_ogg_path="$output_path/$ogg_name"
+if [ ! -d "${OUTPUT_DIR}" ]; then
+    echo "Output directory not found at: ${OUTPUT_DIR}"
+    print_usage
+    exit 1
+fi
 
-    artist=$(metaflac "$flac_path" --show-tag=ARTIST | sed s/.*=//g)
-    title=$(metaflac "$flac_path" --show-tag=TITLE | sed s/.*=//g)
-    album=$(metaflac "$flac_path" --show-tag=ALBUM | sed s/.*=//g)
-    genre=$(metaflac "$flac_path" --show-tag=GENRE | sed s/.*=//g)
-    tracknumber=$(metaflac "$flac_path" --show-tag=TRACKNUMBER | sed s/.*=//g)
-    date=$(metaflac "$flac_path" --show-tag=DATE | sed s/.*=//g)
+INPUT_FILES=$(find ${INPUT_DIR} -type f -name "*.flac" | sort --numeric-sort)
 
-    echo "Converting $flac_path to $output_ogg_path"
-    flac --stdout --silent --decode $flac_path \
+for INPUT_FILEPATH in ${INPUT_FILES}; do
+    INPUT_FILENAME=${INPUT_FILEPATH##*/}
+    OUTPUT_FILENAME="${INPUT_FILENAME%wav}mp3"
+    OUTPUT_FILEPATH="${OUTPUT_DIR}/${OUTPUT_FILENAME}"
+
+    TRACK_ARTIST=$(metaflac "${INPUT_FILEPATH}" --show-tag=ARTIST | sed s/.*=//g)
+    TRACK_TITLE=$(metaflac "${INPUT_FILEPATH}" --show-tag=TITLE | sed s/.*=//g)
+    TRACK_ALBUM=$(metaflac "${INPUT_FILEPATH}" --show-tag=ALBUM | sed s/.*=//g)
+    TRACK_GENRE=$(metaflac "${INPUT_FILEPATH}" --show-tag=GENRE | sed s/.*=//g)
+    TRACK_TRACKNUMBER=$(metaflac "${INPUT_FILEPATH}" --show-tag=TRACKNUMBER | sed s/.*=//g)
+    TRACK_DATE=$(metaflac "${INPUT_FILEPATH}" --show-tag=DATE | sed s/.*=//g)
+
+    echo "Converting ${INPUT_FILEPATH} to ${OUTPUT_FILEPATH}"
+    flac --stdout --silent --decode ${INPUT_FILEPATH} \
         | oggenc - \
-        --quality $quality \
-        --output $output_ogg_path \
-        --artist $artist \
-        --album $album \
-        --genre $genre \
-        --date $date \
-        --tracknum $tracknumber \
-        --title $title
+        --quality ${OGG_QUALITY} \
+        --output ${OUTPUT_FILEPATH} \
+        --artist ${TRACK_ARTIST} \
+        --album ${TRACK_ALBUM} \
+        --genre ${TRACK_GENRE} \
+        --date ${TRACK_DATE} \
+        --tracknum ${TRACK_TRACKNUMBER} \
+        --title ${TRACK_TITLE}
 done
 
-IFS=$SAVEIFS
-
-exit 0
+IFS=${SAVEIFS}
diff --git a/bin/hash_directory b/bin/hash_directory
--- a/bin/hash_directory
+++ b/bin/hash_directory
@@ -2,22 +2,35 @@
 
 set -e
 
-SAVEIFS=$IFS
+SAVEIFS=${IFS}
 IFS=$(echo -en "\n\b")
 
-dir=$(readlink -f $1)
+print_usage() {
+    echo "hash_directory: create an MD5 hash of all files in a directory"
+    echo ""
+    echo "  How to use:"
+    echo "  hash_directory <input_directory>"
+}
 
-if [ ! -d "$dir" ]; then
-    echo "Directory not found"
+INPUT_DIR_ARG=$1
+
+if [ -z "${INPUT_DIR_ARG}" ]; then
+    print_usage
+    exit 1
+fi
+
+INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
+
+if [ ! -d "${INPUT_DIR}" ]; then
+    echo "Input directory not found at: ${INPUT_DIR}"
+    print_usage
     exit 1
 fi
 
 # md5sum must run from directory to keep filenames relative to that directory
-pushd $dir
-echo creating checksums
-md5sum --binary *.flac *.cue *.log > ./checksum.md5
+pushd ${INPUT_DIR}
+echo "Creating checksums for directory: ${INPUT_DIR}"
+md5sum --binary *.mp3 *.flac *.cue *.log > ./checksum.md5
 popd
 
-IFS=$SAVEIFS
-
-exit 0
+IFS=${SAVEIFS}
