Make all scripts work on single or nested directories

diff --git a/bin/flac_to_mp3 b/bin/flac_to_mp3
--- a/bin/flac_to_mp3
+++ b/bin/flac_to_mp3
@@ -12,59 +12,77 @@ print_usage() {
     echo "  flac_to_mp3 <input_directory> <output_directory> [lame-quality, default 2]"
 }
 
-INPUT_DIR_ARG=$1
-OUTPUT_DIR_ARG=$2
-LAME_QUALITY=${3:-2}
+process_dir() {
+    DIR=$1
+    OUTPUT_BASEDIR=$2
+    LAME_QUALITY=$3
 
-if [ -z "${INPUT_DIR_ARG}" ] || [ -z "${OUTPUT_DIR_ARG}" ]; then
-    print_usage
-    exit 1
-fi
+    INPUT_FILES=$(find ${DIR} -type f -name "*.flac" | sort --numeric-sort)
+    OUTPUT_DIR_NAME=$(basename ${DIR})
+    OUTPUT_DIR_PATH=${OUTPUT_BASEDIR}/${OUTPUT_DIR_NAME}
 
-INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
-OUTPUT_DIR=$(readlink -f "${OUTPUT_DIR_ARG}")
+    echo "Creating output directory: ${OUTPUT_DIR_PATH}"
+    mkdir -p ${OUTPUT_DIR_PATH}
 
-if [ ! -d "${INPUT_DIR}" ]; then
-    echo "Input directory not found at: ${INPUT_DIR}"
-    print_usage
-    exit 1
-fi
+    echo "Using lame quality setting: ${LAME_QUALITY}"
 
-if [ ! -d "${OUTPUT_DIR}" ]; then
-    echo "Output directory not found at: ${OUTPUT_DIR}"
-    print_usage
-    exit 1
-fi
+    for INPUT_FILEPATH in ${INPUT_FILES}; do
+        INPUT_FILENAME=${INPUT_FILEPATH##*/}
+        OUTPUT_FILENAME="${INPUT_FILENAME%flac}mp3"
+        OUTPUT_FILEPATH="${OUTPUT_DIR_PATH}/${OUTPUT_FILENAME}"
 
+        TRACK_ARTIST=$(metaflac "${INPUT_FILEPATH}" --show-tag=ARTIST | sed s/.*=//g)
+        TRACK_TITLE=$(metaflac "${INPUT_FILEPATH}" --show-tag=TITLE | sed s/.*=//g)
+        TRACK_ALBUM=$(metaflac "${INPUT_FILEPATH}" --show-tag=ALBUM | sed s/.*=//g)
+        TRACK_GENRE=$(metaflac "${INPUT_FILEPATH}" --show-tag=GENRE | sed s/.*=//g)
+        TRACK_TRACKNUMBER=$(metaflac "${INPUT_FILEPATH}" --show-tag=TRACKNUMBER | sed s/.*=//g)
+        TRACK_DATE=$(metaflac "${INPUT_FILEPATH}" --show-tag=DATE | sed s/.*=//g)
 
-INPUT_FILES=$(find ${INPUT_DIR} -type f -name "*.wav" | sort --numeric-sort)
+        echo "Converting ${INPUT_FILEPATH} to ${OUTPUT_FILEPATH}"
 
-echo "Using lame quality setting: ${LAME_QUALITY}"
+        flac --stdout --silent --decode ${INPUT_FILEPATH} \
+            | lame --silent -V ${LAME_QUALITY} --vbr-new - "${OUTPUT_FILEPATH}"
+        id3v2 \
+            -t "${TRACK_TITLE}" \
+            -T "${TRACK_TRACKNUMBER}" \
+            -a "${TRACK_ARTIST}" \
+            -A "${TRACK_ALBUM}" \
+            -g "${TRACK_GENRE}" \
+            -y "${TRACK_DATE}" \
+            "${OUTPUT_FILEPATH}"
+    done
+}
 
-for INPUT_FILEPATH in ${INPUT_FILES}; do
-    INPUT_FILENAME=${INPUT_FILEPATH##*/}
-    OUTPUT_FILENAME="${INPUT_FILENAME%wav}mp3"
-    OUTPUT_FILEPATH="${OUTPUT_DIR}/${OUTPUT_FILENAME}"
+main() {
+    INPUT_DIR_ARG=$1
+    OUTPUT_DIR_ARG=$2
+    LAME_QUALITY=${3:-2}
 
-    TRACK_ARTIST=$(metaflac "${INPUT_FILEPATH}" --show-tag=ARTIST | sed s/.*=//g)
-    TRACK_TITLE=$(metaflac "${INPUT_FILEPATH}" --show-tag=TITLE | sed s/.*=//g)
-    TRACK_ALBUM=$(metaflac "${INPUT_FILEPATH}" --show-tag=ALBUM | sed s/.*=//g)
-    TRACK_GENRE=$(metaflac "${INPUT_FILEPATH}" --show-tag=GENRE | sed s/.*=//g)
-    TRACK_TRACKNUMBER=$(metaflac "${INPUT_FILEPATH}" --show-tag=TRACKNUMBER | sed s/.*=//g)
-    TRACK_DATE=$(metaflac "${INPUT_FILEPATH}" --show-tag=DATE | sed s/.*=//g)
+    if [ -z "${INPUT_DIR_ARG}" ] || [ -z "${OUTPUT_DIR_ARG}" ]; then
+        print_usage
+        exit 1
+    fi
 
-    echo "Converting ${INPUT_FILEPATH} to ${OUTPUT_FILEPATH}"
+    INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
+    OUTPUT_DIR=$(readlink -f "${OUTPUT_DIR_ARG}")
 
-    flac --stdout --silent --decode ${INPUT_FILEPATH} \
-        | lame --silent -V ${LAME_QUALITY} --vbr-new - "${OUTPUT_FILEPATH}"
-    id3v2 \
-        -t "${TRACK_TITLE}" \
-        -T "${TRACK_TRACKNUMBER}" \
-        -a "${TRACK_ARTIST}" \
-        -A "${TRACK_ALBUM}" \
-        -g "${TRACK_GENRE}" \
-        -y "${TRACK_DATE}" \
-        "${OUTPUT_FILEPATH}"
-done
+    if [ ! -d "${INPUT_DIR}" ]; then
+        echo "Input directory not found at: ${INPUT_DIR}"
+        print_usage
+        exit 1
+    fi
+
+    if [ ! -d "${OUTPUT_DIR}" ]; then
+        echo "Output directory not found at: ${OUTPUT_DIR}"
+        print_usage
+        exit 1
+    fi
+
+    for DIR in $(find ${INPUT_DIR} -links 2 -type d); do
+        process_dir ${DIR} ${OUTPUT_DIR} ${LAME_QUALITY}
+    done
+}
+
+main $@
 
 IFS=${SAVEIFS}
diff --git a/bin/flac_to_ogg b/bin/flac_to_ogg
--- a/bin/flac_to_ogg
+++ b/bin/flac_to_ogg
@@ -10,59 +10,77 @@ print_usage() {
     echo ""
     echo "  How to use:"
     echo "  flac_to_ogg <input_directory> <output_directory> [ogg-quality, default 5]"
+}
 
-INPUT_DIR_ARG=$1
-OUTPUT_DIR_ARG=$2
-OGG_QUALITY=${3:-2}
 
-# Most users agree -q 5 achieves transparency, if the source is the original or
-# lossless: http://wiki.hydrogenaud.io/index.php?title=Recommended_Ogg_Vorbis
+process_dir() {
+    DIR=$1
+    OUTPUT_BASEDIR=$2
+    OGG_QUALITY=$3
 
-if [ -z "${INPUT_DIR_ARG}" ] || [ -z "${OUTPUT_DIR_ARG}" ]; then
-    print_usage
-    exit 1
-fi
+    INPUT_FILES=$(find ${DIR} -type f -name "*.flac" | sort --numeric-sort)
+    OUTPUT_DIR_NAME=$(basename ${DIR})
+    OUTPUT_DIR_PATH=${OUTPUT_BASEDIR}/${OUTPUT_DIR_NAME}
 
-INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
-OUTPUT_DIR=$(readlink -f "${OUTPUT_DIR_ARG}")
+    for INPUT_FILEPATH in ${INPUT_FILES}; do
+        INPUT_FILENAME=${INPUT_FILEPATH##*/}
+        OUTPUT_FILENAME="${INPUT_FILENAME%wav}mp3"
+        OUTPUT_FILEPATH="${OUTPUT_DIR_PATH}/${OUTPUT_FILENAME}"
 
-if [ ! -d "${INPUT_DIR}" ]; then
-    echo "Input directory not found at: ${INPUT_DIR}"
-    print_usage
-    exit 1
-fi
+        TRACK_ARTIST=$(metaflac "${INPUT_FILEPATH}" --show-tag=ARTIST | sed s/.*=//g)
+        TRACK_TITLE=$(metaflac "${INPUT_FILEPATH}" --show-tag=TITLE | sed s/.*=//g)
+        TRACK_ALBUM=$(metaflac "${INPUT_FILEPATH}" --show-tag=ALBUM | sed s/.*=//g)
+        TRACK_GENRE=$(metaflac "${INPUT_FILEPATH}" --show-tag=GENRE | sed s/.*=//g)
+        TRACK_TRACKNUMBER=$(metaflac "${INPUT_FILEPATH}" --show-tag=TRACKNUMBER | sed s/.*=//g)
+        TRACK_DATE=$(metaflac "${INPUT_FILEPATH}" --show-tag=DATE | sed s/.*=//g)
 
-if [ ! -d "${OUTPUT_DIR}" ]; then
-    echo "Output directory not found at: ${OUTPUT_DIR}"
-    print_usage
-    exit 1
-fi
+        echo "Converting ${INPUT_FILEPATH} to ${OUTPUT_FILEPATH}"
+        flac --stdout --silent --decode ${INPUT_FILEPATH} \
+            | oggenc - \
+            --quality ${OGG_QUALITY} \
+            --output ${OUTPUT_FILEPATH} \
+            --artist ${TRACK_ARTIST} \
+            --album ${TRACK_ALBUM} \
+            --genre ${TRACK_GENRE} \
+            --date ${TRACK_DATE} \
+            --tracknum ${TRACK_TRACKNUMBER} \
+            --title ${TRACK_TITLE}
+    done
+}
 
-INPUT_FILES=$(find ${INPUT_DIR} -type f -name "*.flac" | sort --numeric-sort)
+main() {
+    INPUT_DIR_ARG=$1
+    OUTPUT_DIR_ARG=$2
+    OGG_QUALITY=${3:-5}
 
-for INPUT_FILEPATH in ${INPUT_FILES}; do
-    INPUT_FILENAME=${INPUT_FILEPATH##*/}
-    OUTPUT_FILENAME="${INPUT_FILENAME%wav}mp3"
-    OUTPUT_FILEPATH="${OUTPUT_DIR}/${OUTPUT_FILENAME}"
+    # Most users agree -q 5 achieves transparency
+    # See: http://wiki.hydrogenaud.io/index.php?title=Recommended_Ogg_Vorbis
 
-    TRACK_ARTIST=$(metaflac "${INPUT_FILEPATH}" --show-tag=ARTIST | sed s/.*=//g)
-    TRACK_TITLE=$(metaflac "${INPUT_FILEPATH}" --show-tag=TITLE | sed s/.*=//g)
-    TRACK_ALBUM=$(metaflac "${INPUT_FILEPATH}" --show-tag=ALBUM | sed s/.*=//g)
-    TRACK_GENRE=$(metaflac "${INPUT_FILEPATH}" --show-tag=GENRE | sed s/.*=//g)
-    TRACK_TRACKNUMBER=$(metaflac "${INPUT_FILEPATH}" --show-tag=TRACKNUMBER | sed s/.*=//g)
-    TRACK_DATE=$(metaflac "${INPUT_FILEPATH}" --show-tag=DATE | sed s/.*=//g)
+    if [ -z "${INPUT_DIR_ARG}" ] || [ -z "${OUTPUT_DIR_ARG}" ]; then
+        print_usage
+        exit 1
+    fi
 
-    echo "Converting ${INPUT_FILEPATH} to ${OUTPUT_FILEPATH}"
-    flac --stdout --silent --decode ${INPUT_FILEPATH} \
-        | oggenc - \
-        --quality ${OGG_QUALITY} \
-        --output ${OUTPUT_FILEPATH} \
-        --artist ${TRACK_ARTIST} \
-        --album ${TRACK_ALBUM} \
-        --genre ${TRACK_GENRE} \
-        --date ${TRACK_DATE} \
-        --tracknum ${TRACK_TRACKNUMBER} \
-        --title ${TRACK_TITLE}
-done
+    INPUT_DIR=$(readlink -f "${INPUT_DIR_ARG}")
+    OUTPUT_DIR=$(readlink -f "${OUTPUT_DIR_ARG}")
+
+    if [ ! -d "${INPUT_DIR}" ]; then
+        echo "Input directory not found at: ${INPUT_DIR}"
+        print_usage
+        exit 1
+    fi
+
+    if [ ! -d "${OUTPUT_DIR}" ]; then
+        echo "Output directory not found at: ${OUTPUT_DIR}"
+        print_usage
+        exit 1
+    fi
+
+    for DIR in $(find ${INPUT_DIR} -links 2 -type d); do
+        process_dir ${DIR} ${OUTPUT_DIR} ${OGG_QUALITY}
+    done
+}
+
+main $@
 
 IFS=${SAVEIFS}
